version: "3.3"
services:
  worker-ray:
    build: .
    image: morpheus-worker-local:latest
    command: bash start.sh "rtx4090"
    ports:
      - "8000:8000"
      - "8265:8265"

  worker-ray-deployer:
    image: morpheus-worker-local:latest
    command: bash -c "sleep 5 && ray job submit -- serve deploy models.yaml"
    environment:
      - RAY_ADDRESS=http://worker-ray:8265
    depends_on:
      worker-ray:
        condition: service_started

  worker-ray-worker:
    image: morpheus-worker-local:latest
    command: ray start --num-gpus=5 --address='worker-ray:6379' --block
    depends_on:
      worker-ray:
        condition: service_started
