proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

applications:

- name: sd_app

  route_prefix: /

  import_path: app:app

  runtime_env: {}

  deployments:

  - name: GradioIngress
